---
label: product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
pages:
- content/english/products/casa-de-papel.md
- content/english/products/iron-man.md
- content/english/products/stitch.md
